on:
  pull_request:
  push:
    branches: ['main']

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        jvm: ['temurin:21', 'temurin:11']
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: ${{ matrix.jvm }}
      - run: scala-cli test .
      - name: "Check: formatter script shouldn't create a diff on clean tree"
        run: |
          scala-cli run . --main-class scripts.rewrite_src_sc
          [ -n "$(git status --porcelain)" ]
